name: Static Analysis

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31

      - name: lint
        run: |
          nix develop --impure -c treefmt --ci --config-file treefmt.lint.toml
